// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {promptkit} from '../models';
import {mcp} from '../models';
import {context} from '../models';

export function AddUser(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckAndSetupPaths():Promise<void>;

export function CheckAssets():Promise<boolean>;

export function CheckHealth():Promise<core.HealthCheckResult>;

export function ClearDebugTrace():Promise<void>;

export function ConfirmAndRunStorageMigration():Promise<string>;

export function DeleteUser(arg1:string):Promise<void>;

export function DismissWelcome():Promise<void>;

export function DownloadAssets():Promise<void>;

export function EnsureModelsRootDir():Promise<string>;

export function ExportEmbeddingModelManifest():Promise<string>;

export function FetchAndCacheModels():Promise<Array<number>>;

export function GenerateCertificate(arg1:string):Promise<void>;

export function GetAutoStartServer():Promise<boolean>;

export function GetCachedModels():Promise<Array<number>>;

export function GetCertDomain():Promise<string>;

export function GetDebugTraceEnabled():Promise<boolean>;

export function GetDebugTraceEntries():Promise<Array<core.DebugTraceEntry>>;

export function GetEmbeddingModelConfig():Promise<core.EmbeddingModelConfig>;

export function GetLLMApiToken():Promise<string>;

export function GetLicenseText():Promise<string>;

export function GetManagedModelDownloads():Promise<Array<core.ManagedModelDownloadState>>;

export function GetManagedModels():Promise<Array<core.ManagedModelStatus>>;

export function GetMinimizeToTray():Promise<boolean>;

export function GetModelsRootDir():Promise<string>;

export function GetServerStatus():Promise<Record<string, any>>;

export function GetStartOnBoot():Promise<boolean>;

export function GetSystemPrompts():Promise<Array<promptkit.SystemPrompt>>;

export function GetTTSConfig():Promise<core.ServerTTSConfig>;

export function GetTTSDictionary(arg1:string):Promise<Record<string, string>>;

export function GetToolPattern(arg1:string):Promise<Record<string, string>>;

export function GetUserApiToken(arg1:string):Promise<string>;

export function GetUserDetail(arg1:string):Promise<Record<string, any>>;

export function GetUserDisabledTools(arg1:string):Promise<Array<string>>;

export function GetUserDisallowedCommands(arg1:string):Promise<Array<string>>;

export function GetUserDisallowedDirectories(arg1:string):Promise<Array<string>>;

export function GetUserMemoryRetentionConfig(arg1:string):Promise<mcp.MemoryRetentionConfig>;

export function GetUsers():Promise<Array<Record<string, string>>>;

export function GetVoiceStyles():Promise<Array<string>>;

export function GetWelcomeState():Promise<core.WelcomeState>;

export function LearnToolPattern(arg1:string,arg2:string):Promise<void>;

export function LoadModel(arg1:string):Promise<void>;

export function LogoutAllSessions():Promise<void>;

export function OpenCertFolder():Promise<void>;

export function OpenMemoryFolder(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function ResetMemory(arg1:string):Promise<string>;

export function RestartServer():Promise<void>;

export function RunStorageMigration():Promise<string>;

export function SetAutoStartServer(arg1:boolean):Promise<void>;

export function SetCertDomain(arg1:string):Promise<void>;

export function SetDebugTraceEnabled(arg1:boolean):Promise<void>;

export function SetEmbeddingModelConfig(arg1:core.EmbeddingModelConfig):Promise<void>;

export function SetEnableMCP(arg1:boolean):Promise<void>;

export function SetEnableTTS(arg1:boolean):Promise<void>;

export function SetLLMApiToken(arg1:string):Promise<void>;

export function SetLLMEndpoint(arg1:string):Promise<void>;

export function SetLLMMode(arg1:string):Promise<void>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function SetPort(arg1:string):Promise<void>;

export function SetServerTTSConfig(arg1:core.ServerTTSConfig):Promise<void>;

export function SetStartOnBoot(arg1:boolean):Promise<void>;

export function SetTTSConfig(arg1:string,arg2:number):Promise<void>;

export function SetTTSThreads(arg1:number):Promise<void>;

export function SetUserApiToken(arg1:string,arg2:string):Promise<void>;

export function SetUserDisabledTools(arg1:string,arg2:Array<string>):Promise<void>;

export function SetUserDisallowedCommands(arg1:string,arg2:Array<string>):Promise<void>;

export function SetUserDisallowedDirectories(arg1:string,arg2:Array<string>):Promise<void>;

export function SetUserMemoryRetentionConfig(arg1:string,arg2:mcp.MemoryRetentionConfig):Promise<void>;

export function Show():Promise<void>;

export function ShowAbout():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartManagedModelDownload(arg1:string):Promise<void>;

export function StartMemoryWorker():Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StartServerWithCurrentConfig():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopServer():Promise<void>;

export function UpdateUserPassword(arg1:string,arg2:string):Promise<void>;

export function UpdateUserRole(arg1:string,arg2:string):Promise<void>;
