// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2, arg3) {
  return window['go']['core']['App']['AddUser'](arg1, arg2, arg3);
}

export function CheckAndSetupPaths() {
  return window['go']['core']['App']['CheckAndSetupPaths']();
}

export function CheckAssets() {
  return window['go']['core']['App']['CheckAssets']();
}

export function CheckHealth() {
  return window['go']['core']['App']['CheckHealth']();
}

export function ClearDebugTrace() {
  return window['go']['core']['App']['ClearDebugTrace']();
}

export function ConfirmAndRunStorageMigration() {
  return window['go']['core']['App']['ConfirmAndRunStorageMigration']();
}

export function DeleteUser(arg1) {
  return window['go']['core']['App']['DeleteUser'](arg1);
}

export function DismissWelcome() {
  return window['go']['core']['App']['DismissWelcome']();
}

export function DownloadAssets() {
  return window['go']['core']['App']['DownloadAssets']();
}

export function EnsureModelsRootDir() {
  return window['go']['core']['App']['EnsureModelsRootDir']();
}

export function ExportEmbeddingModelManifest() {
  return window['go']['core']['App']['ExportEmbeddingModelManifest']();
}

export function FetchAndCacheModels() {
  return window['go']['core']['App']['FetchAndCacheModels']();
}

export function GenerateCertificate(arg1) {
  return window['go']['core']['App']['GenerateCertificate'](arg1);
}

export function GetAutoStartServer() {
  return window['go']['core']['App']['GetAutoStartServer']();
}

export function GetCachedModels() {
  return window['go']['core']['App']['GetCachedModels']();
}

export function GetCertDomain() {
  return window['go']['core']['App']['GetCertDomain']();
}

export function GetDebugTraceEnabled() {
  return window['go']['core']['App']['GetDebugTraceEnabled']();
}

export function GetDebugTraceEntries() {
  return window['go']['core']['App']['GetDebugTraceEntries']();
}

export function GetEmbeddingModelConfig() {
  return window['go']['core']['App']['GetEmbeddingModelConfig']();
}

export function GetLLMApiToken() {
  return window['go']['core']['App']['GetLLMApiToken']();
}

export function GetLicenseText() {
  return window['go']['core']['App']['GetLicenseText']();
}

export function GetManagedModelDownloads() {
  return window['go']['core']['App']['GetManagedModelDownloads']();
}

export function GetManagedModels() {
  return window['go']['core']['App']['GetManagedModels']();
}

export function GetMinimizeToTray() {
  return window['go']['core']['App']['GetMinimizeToTray']();
}

export function GetModelsRootDir() {
  return window['go']['core']['App']['GetModelsRootDir']();
}

export function GetServerStatus() {
  return window['go']['core']['App']['GetServerStatus']();
}

export function GetStartOnBoot() {
  return window['go']['core']['App']['GetStartOnBoot']();
}

export function GetSystemPrompts() {
  return window['go']['core']['App']['GetSystemPrompts']();
}

export function GetTTSConfig() {
  return window['go']['core']['App']['GetTTSConfig']();
}

export function GetTTSDictionary(arg1) {
  return window['go']['core']['App']['GetTTSDictionary'](arg1);
}

export function GetToolPattern(arg1) {
  return window['go']['core']['App']['GetToolPattern'](arg1);
}

export function GetUserApiToken(arg1) {
  return window['go']['core']['App']['GetUserApiToken'](arg1);
}

export function GetUserDetail(arg1) {
  return window['go']['core']['App']['GetUserDetail'](arg1);
}

export function GetUserDisabledTools(arg1) {
  return window['go']['core']['App']['GetUserDisabledTools'](arg1);
}

export function GetUserDisallowedCommands(arg1) {
  return window['go']['core']['App']['GetUserDisallowedCommands'](arg1);
}

export function GetUserDisallowedDirectories(arg1) {
  return window['go']['core']['App']['GetUserDisallowedDirectories'](arg1);
}

export function GetUserMemoryRetentionConfig(arg1) {
  return window['go']['core']['App']['GetUserMemoryRetentionConfig'](arg1);
}

export function GetUsers() {
  return window['go']['core']['App']['GetUsers']();
}

export function GetVoiceStyles() {
  return window['go']['core']['App']['GetVoiceStyles']();
}

export function GetWelcomeState() {
  return window['go']['core']['App']['GetWelcomeState']();
}

export function LearnToolPattern(arg1, arg2) {
  return window['go']['core']['App']['LearnToolPattern'](arg1, arg2);
}

export function LoadModel(arg1) {
  return window['go']['core']['App']['LoadModel'](arg1);
}

export function LogoutAllSessions() {
  return window['go']['core']['App']['LogoutAllSessions']();
}

export function OpenCertFolder() {
  return window['go']['core']['App']['OpenCertFolder']();
}

export function OpenMemoryFolder(arg1) {
  return window['go']['core']['App']['OpenMemoryFolder'](arg1);
}

export function Quit() {
  return window['go']['core']['App']['Quit']();
}

export function ResetMemory(arg1) {
  return window['go']['core']['App']['ResetMemory'](arg1);
}

export function RestartServer() {
  return window['go']['core']['App']['RestartServer']();
}

export function RunStorageMigration() {
  return window['go']['core']['App']['RunStorageMigration']();
}

export function SetAutoStartServer(arg1) {
  return window['go']['core']['App']['SetAutoStartServer'](arg1);
}

export function SetCertDomain(arg1) {
  return window['go']['core']['App']['SetCertDomain'](arg1);
}

export function SetDebugTraceEnabled(arg1) {
  return window['go']['core']['App']['SetDebugTraceEnabled'](arg1);
}

export function SetEmbeddingModelConfig(arg1) {
  return window['go']['core']['App']['SetEmbeddingModelConfig'](arg1);
}

export function SetEnableMCP(arg1) {
  return window['go']['core']['App']['SetEnableMCP'](arg1);
}

export function SetEnableTTS(arg1) {
  return window['go']['core']['App']['SetEnableTTS'](arg1);
}

export function SetLLMApiToken(arg1) {
  return window['go']['core']['App']['SetLLMApiToken'](arg1);
}

export function SetLLMEndpoint(arg1) {
  return window['go']['core']['App']['SetLLMEndpoint'](arg1);
}

export function SetLLMMode(arg1) {
  return window['go']['core']['App']['SetLLMMode'](arg1);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['core']['App']['SetMinimizeToTray'](arg1);
}

export function SetPort(arg1) {
  return window['go']['core']['App']['SetPort'](arg1);
}

export function SetServerTTSConfig(arg1) {
  return window['go']['core']['App']['SetServerTTSConfig'](arg1);
}

export function SetStartOnBoot(arg1) {
  return window['go']['core']['App']['SetStartOnBoot'](arg1);
}

export function SetTTSConfig(arg1, arg2) {
  return window['go']['core']['App']['SetTTSConfig'](arg1, arg2);
}

export function SetTTSThreads(arg1) {
  return window['go']['core']['App']['SetTTSThreads'](arg1);
}

export function SetUserApiToken(arg1, arg2) {
  return window['go']['core']['App']['SetUserApiToken'](arg1, arg2);
}

export function SetUserDisabledTools(arg1, arg2) {
  return window['go']['core']['App']['SetUserDisabledTools'](arg1, arg2);
}

export function SetUserDisallowedCommands(arg1, arg2) {
  return window['go']['core']['App']['SetUserDisallowedCommands'](arg1, arg2);
}

export function SetUserDisallowedDirectories(arg1, arg2) {
  return window['go']['core']['App']['SetUserDisallowedDirectories'](arg1, arg2);
}

export function SetUserMemoryRetentionConfig(arg1, arg2) {
  return window['go']['core']['App']['SetUserMemoryRetentionConfig'](arg1, arg2);
}

export function Show() {
  return window['go']['core']['App']['Show']();
}

export function ShowAbout() {
  return window['go']['core']['App']['ShowAbout']();
}

export function Shutdown(arg1) {
  return window['go']['core']['App']['Shutdown'](arg1);
}

export function StartManagedModelDownload(arg1) {
  return window['go']['core']['App']['StartManagedModelDownload'](arg1);
}

export function StartMemoryWorker() {
  return window['go']['core']['App']['StartMemoryWorker']();
}

export function StartServer(arg1) {
  return window['go']['core']['App']['StartServer'](arg1);
}

export function StartServerWithCurrentConfig() {
  return window['go']['core']['App']['StartServerWithCurrentConfig']();
}

export function Startup(arg1) {
  return window['go']['core']['App']['Startup'](arg1);
}

export function StopServer() {
  return window['go']['core']['App']['StopServer']();
}

export function UpdateUserPassword(arg1, arg2) {
  return window['go']['core']['App']['UpdateUserPassword'](arg1, arg2);
}

export function UpdateUserRole(arg1, arg2) {
  return window['go']['core']['App']['UpdateUserRole'](arg1, arg2);
}
