// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddUser'](arg1, arg2, arg3);
}

export function CheckAndSetupPaths() {
  return window['go']['main']['App']['CheckAndSetupPaths']();
}

export function CheckAssets() {
  return window['go']['main']['App']['CheckAssets']();
}

export function CheckHealth() {
  return window['go']['main']['App']['CheckHealth']();
}

export function ClearDebugTrace() {
  return window['go']['main']['App']['ClearDebugTrace']();
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DownloadAssets() {
  return window['go']['main']['App']['DownloadAssets']();
}

export function FetchAndCacheModels() {
  return window['go']['main']['App']['FetchAndCacheModels']();
}

export function GetAutoStartServer() {
  return window['go']['main']['App']['GetAutoStartServer']();
}

export function GetCachedModels() {
  return window['go']['main']['App']['GetCachedModels']();
}

export function GetCertDomain() {
  return window['go']['main']['App']['GetCertDomain']();
}

export function GetDebugTraceEnabled() {
  return window['go']['main']['App']['GetDebugTraceEnabled']();
}

export function GetDebugTraceEntries() {
  return window['go']['main']['App']['GetDebugTraceEntries']();
}

export function GetLLMApiToken() {
  return window['go']['main']['App']['GetLLMApiToken']();
}

export function GetLicenseText() {
  return window['go']['main']['App']['GetLicenseText']();
}

export function GetMinimizeToTray() {
  return window['go']['main']['App']['GetMinimizeToTray']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetStartOnBoot() {
  return window['go']['main']['App']['GetStartOnBoot']();
}

export function GetSystemPrompts() {
  return window['go']['main']['App']['GetSystemPrompts']();
}

export function GetTTSConfig() {
  return window['go']['main']['App']['GetTTSConfig']();
}

export function GetTTSDictionary(arg1) {
  return window['go']['main']['App']['GetTTSDictionary'](arg1);
}

export function GetToolPattern(arg1) {
  return window['go']['main']['App']['GetToolPattern'](arg1);
}

export function GetUserApiToken(arg1) {
  return window['go']['main']['App']['GetUserApiToken'](arg1);
}

export function GetUserDetail(arg1) {
  return window['go']['main']['App']['GetUserDetail'](arg1);
}

export function GetUserDisabledTools(arg1) {
  return window['go']['main']['App']['GetUserDisabledTools'](arg1);
}

export function GetUserDisallowedCommands(arg1) {
  return window['go']['main']['App']['GetUserDisallowedCommands'](arg1);
}

export function GetUserDisallowedDirectories(arg1) {
  return window['go']['main']['App']['GetUserDisallowedDirectories'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetVoiceStyles() {
  return window['go']['main']['App']['GetVoiceStyles']();
}

export function LearnToolPattern(arg1, arg2) {
  return window['go']['main']['App']['LearnToolPattern'](arg1, arg2);
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function OpenMemoryFolder(arg1) {
  return window['go']['main']['App']['OpenMemoryFolder'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetMemory(arg1) {
  return window['go']['main']['App']['ResetMemory'](arg1);
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function SetAutoStartServer(arg1) {
  return window['go']['main']['App']['SetAutoStartServer'](arg1);
}

export function SetCertDomain(arg1) {
  return window['go']['main']['App']['SetCertDomain'](arg1);
}

export function SetDebugTraceEnabled(arg1) {
  return window['go']['main']['App']['SetDebugTraceEnabled'](arg1);
}

export function SetEnableMCP(arg1) {
  return window['go']['main']['App']['SetEnableMCP'](arg1);
}

export function SetEnableTTS(arg1) {
  return window['go']['main']['App']['SetEnableTTS'](arg1);
}

export function SetLLMApiToken(arg1) {
  return window['go']['main']['App']['SetLLMApiToken'](arg1);
}

export function SetLLMEndpoint(arg1) {
  return window['go']['main']['App']['SetLLMEndpoint'](arg1);
}

export function SetLLMMode(arg1) {
  return window['go']['main']['App']['SetLLMMode'](arg1);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['main']['App']['SetMinimizeToTray'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function SetStartOnBoot(arg1) {
  return window['go']['main']['App']['SetStartOnBoot'](arg1);
}

export function SetTTSConfig(arg1, arg2) {
  return window['go']['main']['App']['SetTTSConfig'](arg1, arg2);
}

export function SetTTSThreads(arg1) {
  return window['go']['main']['App']['SetTTSThreads'](arg1);
}

export function SetUserApiToken(arg1, arg2) {
  return window['go']['main']['App']['SetUserApiToken'](arg1, arg2);
}

export function SetUserDisabledTools(arg1, arg2) {
  return window['go']['main']['App']['SetUserDisabledTools'](arg1, arg2);
}

export function SetUserDisallowedCommands(arg1, arg2) {
  return window['go']['main']['App']['SetUserDisallowedCommands'](arg1, arg2);
}

export function SetUserDisallowedDirectories(arg1, arg2) {
  return window['go']['main']['App']['SetUserDisallowedDirectories'](arg1, arg2);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function StartMemoryWorker() {
  return window['go']['main']['App']['StartMemoryWorker']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StartServerWithCurrentConfig() {
  return window['go']['main']['App']['StartServerWithCurrentConfig']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateUserPassword(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserPassword'](arg1, arg2);
}

export function UpdateUserRole(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserRole'](arg1, arg2);
}
